{
"name":"insight",
"website":"www.wheels27.blogspot.com",
"description":"I share tons of Alpha",
"logo":"https://cdn.discordapp.com/attachments/1049352220895871046/1197151332709175306/image.png",
"twitter":"https://twitter.com/Adeoniye7"
}
