{
"name":"insight",
"website":"www.wheels27.blogspot.com",
"description":"I share tons of Alpha",
"logo":"https://www.google.com/url?sa=i&url=https%3A%2F%2Flogopond.com%2Fjanisweise%2Fshowcase%2Fdetail%2F277584&psig=AOvVaw0r6UPfrWxHwinsghRDEiCQ&ust=1705670928583000&source=images&cd=vfe&ved=0CBUQjhxqFwoTCKjAgMSF54MDFQAAAAAdAAAAABAE",
"twitter":"https://twitter.com/Adeoniye7",
}
