{
"name":"insight",
"website":"www.wheels27.blogspot.com",
"description":"I share tons of Alpha",
"logo":"https://drive.google.com/file/d/1EtHS1fBf6EhmE1K9HpJGW9ZnJZ_BKs0L/view?usp=sharing",
"twitter":"https://twitter.com/Adeoniye7"
}
